blueprint:
  name: Doorbell Automation
  description: >
    # 🔔 Doorbell Automation
    **Version: 1.0**

    This blueprint allows you to set up a doorbell automation that can flash lights,

    play sounds, send notifications, and execute custom actions when a doorbell is pressed.

    You can customize the behavior based on whether anyone is home or not.


    [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/M4M4ZS0Y)
  domain: automation
  source_url: https://raw.githubusercontent.com/Fredrik81/HASS/refs/heads/main/doorbell.yaml
  input:
    button_device:
      name: Doorbell Button (MQTT)
      description: Select the Zigbee2MQTT button to trigger the doorbell.
      selector:
        device:
          filter:
            - integration: mqtt
    media_players:
      name: Media Players
      description: Select media players to play the doorbell sound.
      selector:
        target:
          entity:
            domain: media_player
    send_notification:
      name: Notify Phone
      description: Optionally notify a mobile device.
      default: false
      selector:
        boolean: {}
    notify_target:
      name: Notification Target
      description: Mobile app notify target (e.g. notify.mobile_app_xyz)
      default: []
      selector:
        entity:
          domain: notify

trigger:
  - platform: device
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: single

condition: []

action:
  - service: media_player.play_media
    data:
      media_content_id: >-
        https://raw.githubusercontent.com/Fredrik81/HASS/refs/heads/main/doorbell/doorbell.mp3
      media_content_type: audio/mpeg
    target: !input media_players

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ iif(is_boolean(input.send_notification), input.send_notification, false) }}"
        sequence:
          - service: notify.{{ iif(input.notify_target is string, input.notify_target.split('.')[-1], 'mobile_app') }}
            data:
              title: Dörrklocka alarm!
              message: Någon är vid dörren!