blueprint:
  name: Doorbell Automation
  description: >
    This blueprint allows you to set up a doorbell automation that can flash lights,
    play sounds, send notifications, and execute custom actions when a doorbell is pressed.
    You can customize the behavior based on whether anyone is home or not.
  domain: automation
  input:
    # Global presence config
    presence_zone:
      name: Presence Zone
      default: zone.home
      selector:
        entity:
          domain: zone

    # STOP condition
    stop_entities:
      name: Stop If Any of These Entities Change
      selector:
        target:
          entity:
            domain:
              - binary_sensor
              - lock
      description: "Select entities (e.g., binary sensors or locks) that will stop the automation when their state changes."

    # Lights section
    enable_lights:
      name: Enable Light Flashing
      default: true
      selector:
        boolean: {}
      description: "Enable or disable light flashing when the doorbell is pressed."
    lights_presence_condition:
      name: Flash Lights Presence Condition
      default: always
      selector:
        select:
          options:
            - always
            - only_if_someone_in_zone
            - only_if_no_one_in_zone
    alert_lights:
      name: Lights to Blink
      selector:
        target:
          entity:
            domain: light
    blink_color:
      name: Blink Color
      selector:
        color_rgb: {}
      description: "Optional: Set the color for blinking lights. Leave empty for default behavior."

    # Sound section
    enable_sound:
      name: Enable Sound Playback
      default: true
      selector:
        boolean: {}
    sound_presence_condition:
      name: Play Sound Presence Condition
      default: always
      selector:
        select:
          options:
            - always
            - only_if_someone_in_zone
            - only_if_no_one_in_zone
    media_players:
      name: Media Players
      selector:
        target:
          entity:
            domain: media_player
    media_url:
      name: Media File URL
      selector:
        text: {}
      description: "Enter a valid URL for the media file to play."
      default: "https://raw.githubusercontent.com/Fredrik81/HASS/refs/heads/main/doorbell.mp3"

    # Notifications
    enable_notification:
      name: Enable Notifications
      default: true
      selector:
        boolean: {}
      description: "Enable or disable sending notifications when the doorbell is pressed."

    notification_presence_condition:
      name: Notification Presence Condition
      default: always
      selector:
        select:
          options:
            - always
            - only_if_someone_in_zone
            - only_if_no_one_in_zone
      description: "Specify when notifications should be sent."

    notify_targets:
      name: Notification Targets
      selector:
        target:
          entity:
            domain: notify
      description: "Select one or more notification services to send the notification to."

    notification_title:
      name: Notification Title
      default: "Someone at the door!"
      selector:
        text: {}
      description: "Specify the title of the notification."

    notification_message:
      name: Notification Message
      default: "Someone pressed the doorbell."
      selector:
        text: {}
      description: "Specify the message to send in the notification."

    # Custom Actions
    enable_custom_actions:
      name: Enable Custom Actions
      default: false
      selector:
        boolean: {}
      description: "Enable or disable custom actions when the doorbell is pressed."
    custom_actions_presence_condition:
      name: Custom Actions Presence Condition
      default: always
      selector:
        select:
          options:
            - always
            - only_if_someone_in_zone
            - only_if_no_one_in_zone
    custom_actions:
      name: Custom Actions
      selector:
        action: {}
      description: "Define one or more custom actions to execute when the doorbell is pressed."
