blueprint:
  name: Doorbell Automation
  description: >
    This blueprint allows you to set up a doorbell automation that can flash lights,
    play sounds, and send notifications when a doorbell is pressed. You can customize
    the behavior based on whether anyone is home or not.
  domain: automation
  input:
    # Global presence config
    presence_zone:
      name: Presence Zone
      default: zone.home
      selector:
        entity:
          domain: zone

    # STOP condition
    stop_entities:
      name: Stop If Any of These Entities Change
      selector:
        target:
          entity:
            domain: binary_sensor
      description: "Select entities that will stop the automation when their state changes."

    # Lights section
    enable_lights:
      name: Enable Light Flashing
      default: true
      selector:
        boolean: {}
      description: "Enable or disable light flashing when the doorbell is pressed."
    lights_presence_condition:
      name: Flash Lights Presence Condition
      default: always
      selector:
        select:
          options:
            - always
            - only_if_someone_in_zone
            - only_if_no_one_in_zone
    alert_lights:
      name: Lights to Blink
      selector:
        target:
          entity:
            domain: light
    blink_color:
      name: Blink Color
      selector:
        color_rgb: {}
      description: "Optional: Set the color for blinking lights. Leave empty for default behavior."

    # Sound section
    enable_sound:
      name: Enable Sound Playback
      default: true
      selector:
        boolean: {}
    sound_presence_condition:
      name: Play Sound Presence Condition
      default: always
      selector:
        select:
          options:
            - always
            - only_if_someone_in_zone
            - only_if_no_one_in_zone
    media_players:
      name: Media Players
      selector:
        target:
          entity:
            domain: media_player
    media_url:
      name: Media File URL
      selector:
        text: {}
      description: "Enter a valid URL for the media file to play."
      default: "https://raw.githubusercontent.com/Fredrik81/HASS/refs/heads/main/doorbell.mp3"

    # Notifications
    enable_notification:
      name: Send Notification
      default: true
      selector:
        boolean: {}
    notification_presence_condition:
      name: Notify Presence Condition
      default: always
      selector:
        select:
          options:
            - always
            - only_if_someone_in_zone
            - only_if_no_one_in_zone
    notify_targets:
      name: Devices to Notify
      selector:
        target:
          entity:
            domain: notify
      default: []  # Default to an empty list if no devices are selected
    notification_message:
      name: Message
      selector:
        text: {}
